package views;



import domain.Carnivoro;
import domain.Especie;
import domain.Herbivoro;
import domain.Pais;
import domain.Sector;
import domain.TipoAlimentacion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.InvalidPropertiesFormatException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Guada
 */
public class Agregaranimal extends javax.swing.JFrame {
    
    
    public Agregaranimal() {
        initComponents();
        
         cargarDatosComboBox(this);
         habilitarValorfijo(); 
         inicializarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pesotxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edadtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paistxt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipotxt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        sectortxt = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        especietxt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        valortxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peso: ");

        pesotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesotxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Edad:");

        jLabel3.setText("Pais:");

        paistxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Magascar", "Rusia", "India", "Brasil", "Australia" }));
        paistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paistxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Especie:");

        jLabel5.setText(" Tipo de alimentacion");

        tipotxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnivoro", "Herbivoro" }));
        tipotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipotxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Sector:");

        sectortxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));

        jLabel7.setText("INGRESAR ANIMAL");

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        especietxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leon ", "Tigre", "Jirafa", "Elefante" }));

        jLabel8.setText("Valor Fijo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(especietxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(paistxt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sectortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(edadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(guardar)
                                .addGap(53, 53, 53)
                                .addComponent(volver))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pesotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tipotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(especietxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(paistxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(sectortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(edadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pesotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(volver))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesotxtActionPerformed

    private void tipotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipotxtActionPerformed

    private void paistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paistxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paistxtActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        if (tipotxt.getSelectedItem().toString().equals(TipoAlimentacion.HERBIVORO.toString())) {
            try {
                Controlador.guardarAnimal(new Herbivoro(this.getEdadtxt(), this.getPesotxt(), this.getEspecietxt(), this.getSectortxt(), this.getValortxt(), this.getPaistxt()));
                System.out.println("Animal fue agregado");
                JOptionPane.showMessageDialog(null, "Animal agregado exitosamente", "Animal agregado", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ingrese correctamente el animal", "Error combinacion de datos invalida", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(tipotxt.getSelectedItem().toString().equals(TipoAlimentacion.CARNIVORO.toString())){
            try{
                Controlador.guardarAnimal(new Carnivoro(this.getEdadtxt(), this.getPesotxt(), this.getEspecietxt(), this.getSectortxt(), this.getPaistxt()));
                 JOptionPane.showMessageDialog(null, "Animal agregado exitosamente", "Animal agregado", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception ex){
                ex.printStackTrace();
                 JOptionPane.showMessageDialog(null, "Ingrese correctamente el animal", "Error combinacion de datos invalida", JOptionPane.ERROR_MESSAGE);
            }
        }
       
        
    }//GEN-LAST:event_guardarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
     Controlador.volver(this);
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregaranimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregaranimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregaranimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregaranimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregaranimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edadtxt;
    private javax.swing.JComboBox<String> especietxt;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> paistxt;
    private javax.swing.JTextField pesotxt;
    private javax.swing.JComboBox<String> sectortxt;
    private javax.swing.JComboBox<String> tipotxt;
    private javax.swing.JTextField valortxt;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public int getEdadtxt() {
        return Integer.parseInt(edadtxt.getText());
    }

    public void setEdadtxt(String edad) {
        edadtxt.setText(edad);
    }

    public TipoAlimentacion getTipoAlimentacion(String tipo) {
        try {
            return TipoAlimentacion.valueOf(tipo);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Tipo de alimentación inválido", "Error", JOptionPane.ERROR_MESSAGE);
            return TipoAlimentacion.HERBIVORO; 
        }
    }

    public Especie getEspecietxt() {
    for (Especie especie : Controlador.getEspecies()) {
        if (especie.getNombre().equals(especietxt.getSelectedItem().toString())) {
            return especie;
        }
    }
    JOptionPane.showMessageDialog(this, "Especie no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
    return null;
}


    public void setEspecietxt(javax.swing.JComboBox<String> especietxt) {
        this.especietxt = especietxt;
    }

    public void setPaistxt(javax.swing.JComboBox<String> paistxt) {
        this.paistxt = paistxt;
    }

    public Double getPesotxt() {
        return Double.valueOf(pesotxt.getText());
    }

    public void setPesotxt(javax.swing.JTextField pesotxt) {
        this.pesotxt = pesotxt;
    }

    public Sector getSectortxt() {
        ArrayList<Sector> sectores = Controlador.getSectores();
        for (Sector sector : sectores) {
            if (sector.getNumero() == Integer.parseInt(sectortxt.getSelectedItem().toString())) {
                return sector;
            }
        }
        JOptionPane.showMessageDialog(this, "Seleccionar nuevo Sector", "Error", JOptionPane.ERROR);
        return null;
    }

    public Pais getPaistxt() {
        ArrayList<Pais> paises = Controlador.getPaises();
        for (Pais pais : paises) {
            if (pais.getNombre().equals(paistxt.getSelectedItem().toString())) {
                return pais;
            }
        }
        JOptionPane.showMessageDialog(this, "Seleccionar nuevo Pais", "Error", JOptionPane.ERROR);
        return null;
    }

    public void setSectortxt(javax.swing.JComboBox<String> sectortxt) {
        this.sectortxt = sectortxt;
    }

    public String getTipotxt() {
        return tipotxt.getSelectedItem().toString();
    }

    public void setTipotxt(javax.swing.JComboBox<String> tipotxt) {
        this.tipotxt = tipotxt;
    }

    public Double getValortxt() {
        return Double.valueOf(valortxt.getText());
    }

    public void setValortxt(javax.swing.JTextField valortxt) {
        this.valortxt = valortxt;
    }

    public void cargarDatosComboBox(Agregaranimal vista) {
        
        especietxt.removeAllItems();
        ArrayList<Especie> especies = Controlador.getEspecies();
        for (Especie especie : especies) {
            especietxt.addItem(especie.getNombre());
        }

        sectortxt.removeAllItems();
        ArrayList<Sector> sectores = Controlador.getSectores();
        for (Sector sector : sectores) {
            sectortxt.addItem(String.valueOf(sector.getNumero()));
        }

        paistxt.removeAllItems();
        ArrayList<Pais> paises = Controlador.getPaises();
        for (Pais pais : paises) {
            paistxt.addItem(pais.getNombre());
        }

        tipotxt.removeAllItems();
        for (TipoAlimentacion tipo : Controlador.getTiposAlimentacion()) {
            tipotxt.addItem(tipo.toString());

        }
    }
    
      public void habilitarValorfijo() {
          String tipoSeleccionado = tipotxt.getSelectedItem().toString();
    if (tipoSeleccionado.equals(TipoAlimentacion.HERBIVORO.toString())) {
        valortxt.setEnabled(true);
    } else {
        valortxt.setEnabled(false);
    }
}


     private void inicializarEventos() {
    tipotxt.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String selecciontxt = tipotxt.getSelectedItem().toString();
            if (selecciontxt.equals(TipoAlimentacion.HERBIVORO.toString())) {
                valortxt.setEnabled(true);
            } else {
                valortxt.setEnabled(false);
            }
        }
    });
}
      
}
